Server:
  RunMode: debug
  HttpPort: 8001
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png

DataBase:
  DBType: mysql
  Username: root
  Password: sinowealth
  Host: 192.168.56.1:3306
  DBName: go
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

MusicDataBase:
  DBType: mysql
  Username: ''
  Password: ''
  Host:  ''
  DBName: music
  TablePrefix:
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

JWT:
  Secret: go-blog
  Issuer: blog-service
  Expire: 7200

Email:
  Host: smtp.exmail.qq.com
  Port: 465
  UserName: ''
  Password: ''
  IsSSL: true
  From: ''
  To:
    - ''